repos:
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        pass_filenames: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
  - repo: https://github.com/seddonym/import-linter
    rev: v2.1
    hooks:
      - id: import-linter
        stages: [manual]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.1
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/psf/black
    rev: 3702ba224ecffbcec30af640c149f231d90aebdb # frozen: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: 32151ac97cbfd7f9dcd22e49516fb32266db45b4 # frozen: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

ci:
  autoupdate_schedule: monthly
